In [2]:
import pandas as pd
#import geopandas as gpd
import shapely
from shapely.geometry import Point, MultiPoint
#import fiona
#from pykml import parser
from shapely.ops import nearest_points

still to do:
- check if later version available locally with final merge for visualization
- change link to read 'snow_level' data
- check if better data for swiss_cities, if not:
- add swiss_cities to gitHub
- add testing notebook for NB III to github? or add section to 'proof' it's working in final NB III
- check csv path for swiss cities

In [3]:
path = 'C:/Users/Malwina/Desktop/Data_Science/Bootcamp/Visualization/Bergfex_project_cont/coordinates.csv'
snow = pd.read_csv(path, delimiter = ';', decimal=',')
snow = snow.dropna()
# EPSG:4326/WGS84

path = 'C:/Users/Malwina/Desktop/Data_Science/Bootcamp/Visualization/Bergfex_project_cont/swiss_cities.csv'
points = pd.read_csv(path)

In [17]:
# renaming the snow columns to later be merged with the coordinates of the gps df
snow = snow.rename(columns = {'lat':'near_lat', 'lng':'near_lng'})
# renaming columns for clarity when merging
snow = snow.rename(columns = {'location':'snow_point', 'height_in_m':'snow_alt'})
snow

,snow_point,snow_alt,snowlevel_in_cm,near_lat,near_lng
2,Aigle,381,0,46.319025,6.970566
3,Altdorf,449,0,46.880600,8.639400
4,Andermatt,2282,0,46.602389,8.611800
5,Appenzell,780,0,47.333300,9.416700
6,Beatenberg,1182,0,46.703541,7.809551
7,Binningen,316,0,47.537870,7.570988
8,Bivio,1856,0,46.467767,9.650451
9,Blatten,1535,1,46.420105,7.820000
11,Bosco Gurin,1480,0,46.316402,8.492653
12,Buchs-Suhr,387,0,47.165540,9.470859
13,Bullet,1202,0,46.830796,6.554367
15,Chaumont,0,0,47.032598,6.964280
16,Chuenisbaergli-Schneehoehe,0,3,46.472472,7.546399
17,Chur,555,0,46.852100,9.529700
19,Corviglia,2497,3,46.507556,9.819000
20,Crans-Montana,1427,0,46.311858,7.482353
21,Davos,1590,0,46.809100,9.839800
22,Disentis,1190,0,46.705113,8.852375
23,Echandens,422,0,46.535202,6.541900
24,Elm,965,0,46.929611,9.141000
25,Engelberg,1035,0,46.790917,8.387700
27,Geneva,420,0,46.200000,6.150000
28,Glattalp,1858,15,46.919733,8.903842
29,Graechen,0,0,46.196585,7.839791
30,Grimsel-Hospiz,1980,1,46.572520,8.333860
32,Hornli,1144,0,47.370900,8.941920
33,Juf,2050,0,46.445556,9.579167
34,Kussnacht,520,0,47.085600,8.442100
35,La Chaux-de-Fonds,1019,1,47.099600,6.829600
36,La Dole,1670,0,46.425400,6.099580
37,Lenzerheide,1484,3,46.742500,9.598100
38,Locarno-Monti,366,0,46.171747,8.790342
40,Marsens,0,0,46.655876,7.064416
42,Meiringen,595,0,46.725161,8.190908
50,Pontresina,1904,0,46.492996,9.902496
53,Saas Fee,1790,0,46.109107,7.929712
54,Samedan,1705,1,46.533994,9.872934
57,Santis,2490,20,47.249385,9.343234
58,Schwagalp,1350,4,47.255800,9.308080
59,Scuol/Schuls,1298,0,46.796872,10.297738
64,St. Gallen,779,0,47.423300,9.377200
65,Trubschachen-Blapbach,1091,0,46.890466,7.821042
66,Ulrichen,1345,0,46.506592,8.304801
68,Vals (GR),1255,0,46.617845,9.180474
70,Wadenswil,463,0,47.230300,8.672200
73,Zermatt,1638,0,45.983056,7.782200
74,Zollikofen,553,0,46.998256,7.451340
76,Zurich,432,0,47.378600,8.540000

In [5]:
snow.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 2 to 76
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   location         48 non-null     object
 1   height_in_m      48 non-null     int64
 2   snowlevel_in_cm  48 non-null     int64
 3   lat              48 non-null     float64
 4   lng              48 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.2+ KB

In [6]:
# we want to calculate the closest point in that df to another gps point
test_points = points.iloc[0:10, 0:4] # selecting a test set for the calculation
test_points

   Unnamed: 0          city      lat     lng
0           0        Zürich  47.3786  8.5400
1           1        Geneva  46.2000  6.1500
2           2         Basel  47.5606  7.5906
3           3      Lausanne  46.5333  6.6333
4           4          Bern  46.9480  7.4474
5           5    Winterthur  47.4992  8.7267
6           6       Lucerne  47.0523  8.3059
7           7  Sankt Gallen  47.4233  9.3772
8           8        Lugano  46.0103  8.9625
9           9   Biel/Bienne  47.1372  7.2472

In [7]:
# making a single multipoint object out of all the snow points (3 to test)
# making Points out of the snow points

# creating a grid out of all the snow points in the df snow
snow_point_list= []

for index, row in snow.iterrows():
    point = Point(row['near_lat'], row['near_lng'])
    snow_point_list.append(point)
    
len(snow_point_list) # 48 locations 

snow_grid = MultiPoint(snow_point_list)

In [8]:
# finding which snow point is nearest to the test point 
nearest_list = [] # list that contains tuples of nearest snow point in Point object format
near_lng = []  # contains the longitudes of the nearest snow point extracted from nearest shapely calculation
near_lat = []  # latitudes 

for index, row in test_points.iterrows():
    tested_point = Point(row['lat'], row['lng'])
    nearest = nearest_points(tested_point, snow_grid)
    nearest_list.append(nearest[1]) # the second item in the tuple is the nearest point

for i in range(len(nearest_list)):
    near_lng.append(nearest_list[i].y) 
    near_lat.append(nearest_list[i].x)

In [9]:
len(near_lng)

10

In [10]:
# adding the coordinates of the nearest snow point to each row of the hike df

gps_df = test_points

gps_df['near_lat'] = near_lat
gps_df['near_lng'] = near_lng

In [11]:
gps_df

   Unnamed: 0          city      lat     lng   near_lat  near_lng
0           0        Zürich  47.3786  8.5400  47.378600  8.540000
1           1        Geneva  46.2000  6.1500  46.200000  6.150000
2           2         Basel  47.5606  7.5906  47.537870  7.570988
3           3      Lausanne  46.5333  6.6333  46.535202  6.541900
4           4          Bern  46.9480  7.4474  46.998256  7.451340
5           5    Winterthur  47.4992  8.7267  47.378600  8.540000
6           6       Lucerne  47.0523  8.3059  47.085600  8.442100
7           7  Sankt Gallen  47.4233  9.3772  47.423300  9.377200
8           8        Lugano  46.0103  8.9625  46.171747  8.790342
9           9   Biel/Bienne  47.1372  7.2472  46.998256  7.451340

In [16]:
# now we need to match those calculated nearest coordinates with the name of the snow_point with same coordinates
# we merge the two dataframes on coordinates, with replicating the rows of snow points if necessary
# merged should have length of gps dataframe rows
merged = pd.merge(gps_df, snow, on=['near_lat','near_lng'])
merged

,Unnamed: 0,city,lat,lng,near_lat,near_lng,snow_point,snow_alt,snowlevel_in_cm
0,0,Zürich,47.3786,8.5400,47.378600,8.540000,Zurich,432,0
1,5,Winterthur,47.4992,8.7267,47.378600,8.540000,Zurich,432,0
2,1,Geneva,46.2000,6.1500,46.200000,6.150000,Geneva,420,0
3,2,Basel,47.5606,7.5906,47.537870,7.570988,Binningen,316,0
4,3,Lausanne,46.5333,6.6333,46.535202,6.541900,Echandens,422,0
5,4,Bern,46.9480,7.4474,46.998256,7.451340,Zollikofen,553,0
6,9,Biel/Bienne,47.1372,7.2472,46.998256,7.451340,Zollikofen,553,0
7,6,Lucerne,47.0523,8.3059,47.085600,8.442100,Kussnacht,520,0
8,7,Sankt Gallen,47.4233,9.3772,47.423300,9.377200,St. Gallen,779,0
9,8,Lugano,46.0103,8.9625,46.171747,8.790342,Locarno-Monti,366,0

In [ ]:
# We want to make sure our snow level is actually relevant: 
# Condition 1 : the snow point has to be less than 30 km away from the hike (30 km is in between the average resolution of the
# snow thickness maps of SLF, the hi res being 2-5 km, the larger one around 50)

# Calculating the distance between gps point and nearest point




# df[“release_date”] = df[[‘release_year’, ‘release_month’, ‘release_day’]].apply(lambda x : dt.datetime(*x), axis = 1)

In [ ]:
# Condition 2 : # filter on altitude max <1000 m difference 
# We chose 1000 m because it's the resolution of SLF data
# if the snow measurement was done more than 1000 m lower than the max alt of the hike, we want a warning saying potential snow
# if the measurement is more than 1000 m higher than the max alt, we want a message saying the hike is low altitude
# if any snow point in a radius of 80 km of a lower altitude has snow, we want a snow warning
# if the measurement is within 1000 m up and down of the highest point, we consider it accurate